# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5v6iru55KzRD1zk9Xhe16kswPYRsFxW
"""

!pip install -q pypdf scikit-learn openai faiss-cpu sentence-transformers

import getpass

GROK_API_KEY = getpass.getpass("Paste your Grok (xAI) API key: ")

import os
from dataclasses import dataclass
from typing import List
from pypdf import PdfReader


@dataclass
class Chunk:
    text: str
    source: str
    chunk_id: int


def _read_txt(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        return f.read()


def _read_pdf(path: str) -> str:
    reader = PdfReader(path)
    return "\n".join(page.extract_text() or "" for page in reader.pages)


def load_documents(docs_dir: str):
    docs = []
    for fname in sorted(os.listdir(docs_dir)):
        path = os.path.join(docs_dir, fname)
        ext = os.path.splitext(fname)[1].lower()
        if ext in (".txt", ".md"):
            text = _read_txt(path)
        elif ext == ".pdf":
            text = _read_pdf(path)
        else:
            continue
        docs.append((fname, text))
    return docs


def chunk_text(text: str, chunk_size: int = 500, overlap: int = 50) -> List[str]:
    text = " ".join(text.split())
    if not text:
        return []
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunks.append(text[start:end])
        start = end - overlap
        if start <= 0:
            break
    return chunks


def build_chunks(docs_dir: str, chunk_size: int = 500, overlap: int = 50) -> List[Chunk]:
    all_chunks = []
    for filename, text in load_documents(docs_dir):
        for i, piece in enumerate(chunk_text(text, chunk_size, overlap)):
            all_chunks.append(Chunk(text=piece, source=filename, chunk_id=i))
    return all_chunks

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

EMBED_MODEL_NAME = "all-MiniLM-L6-v2"


class VectorStore:
    def __init__(self):
        self.embedder = SentenceTransformer(EMBED_MODEL_NAME)
        self.chunks = []
        self.faiss_index = None

    def _embed(self, texts):
        vecs = self.embedder.encode(texts, normalize_embeddings=True)
        return np.array(vecs, dtype="float32")

    def index(self, chunks):
        self.chunks = chunks
        vecs = self._embed([c.text for c in chunks])
        dim = vecs.shape[1]
        self.faiss_index = faiss.IndexFlatIP(dim)
        self.faiss_index.add(vecs)

    def search(self, query: str, top_k: int = 3):
        if self.faiss_index is None or len(self.chunks) == 0:
            return []
        query_vec = self._embed([query])
        scores, idxs = self.faiss_index.search(query_vec, top_k)
        results = []
        for score, idx in zip(scores[0], idxs[0]):
            if idx == -1:
                continue
            results.append((self.chunks[idx], float(score)))
        return results

from openai import OpenAI

client = OpenAI(api_key=GROK_API_KEY, base_url="https://api.groq.com/openai/v1")

SCORE_THRESHOLD = 0.08


def answer_with_grok(question: str, results) -> str:
    if not results or results[0][1] < SCORE_THRESHOLD:
        return "I don't know. That isn't covered in the documents I have."

    context = "\n\n".join(
        f"[Source: {c.source}, chunk #{c.chunk_id}]\n{c.text}"
        for c, score in results
    )

    system = (
        "Answer ONLY using the provided context. Every answer must name "
        "the source file it came from. If the context does not contain "
        "the answer, say exactly: \"I don't know based on the provided "
        "documents.\" Never use outside knowledge."
    )
    prompt = f"Context:\n{context}\n\nQuestion: {question}"
    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",  # current Groq flagship general-purpose model
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": prompt},
        ],
        max_tokens=400,
    )


    return response.choices[0].message.content


def ask(store: VectorStore, question: str, top_k: int = 3):
    results = store.search(question, top_k=top_k)

    print(f"\nQ: {question}")
    print("-- retrieved chunks --")
    for c, score in results:
        preview = c.text.strip()[:80].replace("\n", " ")
        print(f"  [{score:.2f}] {c.source} (chunk #{c.chunk_id}): {preview}...")

    answer = answer_with_grok(question, results)
    print(f"A: {answer}")
    return answer

import os
from google.colab import files

DOCS_DIR = "docs"
os.makedirs(DOCS_DIR, exist_ok=True)

uploaded = files.upload()
for fname, content in uploaded.items():
    with open(os.path.join(DOCS_DIR, fname), "wb") as f:
        f.write(content)

print("Uploaded:", list(uploaded.keys()))

CHUNK_SIZE = 500
OVERLAP = 50

chunks = build_chunks(DOCS_DIR, chunk_size=CHUNK_SIZE, overlap=OVERLAP)
store = VectorStore()
store.index(chunks)
print(f"Indexed {len(chunks)} chunks from {DOCS_DIR} (chunk_size={CHUNK_SIZE}, overlap={OVERLAP})")

# Replace with a real question about your documents
ask(store, "What are the benefits of AirFiber_1199_1M plan")

# Should trigger "I don't know" — checks that fallback works
ask(store, "What is the capital of mongolia ?")

test_questions = [
    "What are the benefits of AirFiber_1199_1M plan",
    "What is the capital of mongolia ?",
]

for size in [150, 500, 1200]:
    print("\n" + "=" * 60)
    print(f"CHUNK_SIZE = {size}")
    print("=" * 60)
    exp_chunks = build_chunks(DOCS_DIR, chunk_size=size, overlap=int(size * 0.1))
    exp_store = VectorStore()
    exp_store.index(exp_chunks)
    for q in test_questions:
        results = exp_store.search(q, top_k=1)
        if results:
            c, score = results[0]
            print(f"  [{score:.2f}] {q}  ->  {c.source} (chunk #{c.chunk_id})")