"""
Tests for the Week 4 bonus (MMR) and for the Week 3 report artifacts the
assignment grades directly.

Both halves of results.md are generated, so the guarantee worth pinning is not
the numbers - they move when the corpus moves - but that the artifacts the
rubric asks for are present and that MMR stays switchable off.
"""

from pathlib import Path

import pytest

from app.services.rag_service import MIN_CANDIDATES, VectorStore, build_chunks
from app.services.retrieval import minmax, mmr_select

SAMPLE_ROOT = Path(__file__).resolve().parents[2] / "sample_documents"
RESULTS = Path(__file__).resolve().parents[2] / "results.md"


@pytest.fixture(scope="module")
def store():
    chunks = build_chunks(str(SAMPLE_ROOT), chunk_size=1000, overlap=100, strategy="heading")
    vs = VectorStore()
    vs.index(chunks)
    return vs


def test_minmax_survives_a_flat_score_map():
    """A candidate pool where every score ties must not divide by zero."""
    assert minmax({}) == {}
    assert minmax({1: 0.5, 2: 0.5}) == {1: 1.0, 2: 1.0}
    assert minmax({1: 0.0, 2: 1.0, 3: 0.5}) == {1: 0.0, 2: 1.0, 3: 0.5}


def test_mmr_at_lambda_one_is_the_identity():
    """
    lam = 1.0 must reproduce the input order exactly. That is what lets the
    bonus sweep use a single code path for its control row instead of branching
    around MMR, so the 'MMR off' row really is the shipped retriever.
    """
    order = [3, 1, 2, 0]
    relevance = {3: 1.0, 1: 0.7, 2: 0.4, 0: 0.1}
    assert mmr_select(order, relevance, lambda a, b: 1.0, 4, 1.0) == order


def test_mmr_at_lambda_zero_ignores_relevance_and_spreads_out():
    """
    With lam = 0 only the diversity term counts, so after the first pick the
    least similar candidate wins regardless of how relevant it is.
    """
    order = [0, 1, 2]
    relevance = {0: 1.0, 1: 0.9, 2: 0.0}
    similarity = {(0, 1): 0.99, (0, 2): 0.01, (1, 2): 0.5}

    def sim(a, b):
        return similarity.get((a, b)) or similarity.get((b, a)) or 0.0

    assert mmr_select(order, relevance, sim, 2, 0.0) == [0, 2]


def test_search_hybrid_leaves_the_shipped_ranking_alone_by_default(store):
    """
    MMR is the bonus experiment, not the shipped retriever. The default call and
    an explicit lam = 1.0 must return the same order, or section 14's numbers
    would describe a pipeline the app does not run.
    """
    query = "What OTT apps are included with AirFiber_1199_1M?"
    default = [c.chunk_id for c, _ in store.search_hybrid(query, top_k=5)]
    identity = [c.chunk_id for c, _ in store.search_hybrid(query, top_k=5, mmr_lambda=1.0)]
    assert default == identity


def test_mmr_actually_changes_the_ranking_at_a_low_lambda(store):
    """
    If a low lambda left the order untouched, the bonus sweep would report a
    flat table and quietly prove nothing.
    """
    query = "What OTT apps are included with AirFiber_1199_1M?"
    shipped = [c.chunk_id for c, _ in store.search_hybrid(query, top_k=5)]
    diversified = [c.chunk_id for c, _ in store.search_hybrid(query, top_k=5, mmr_lambda=0.3)]
    assert shipped != diversified


def test_mmr_returns_the_requested_number_of_results(store):
    for lam in (0.3, 0.5, 0.9):
        assert len(store.search_hybrid("error code AF-511", top_k=3, mmr_lambda=lam)) == 3


def test_the_rerank_pool_covers_the_top_25_the_assignment_specifies(store):
    """
    Week 4 Task Set A names 'a cross-encoder rerank over the top 25'. The pool is
    max(top_k * 4, MIN_CANDIDATES), so the floor is what carries that at small
    top_k - at top_k = 3 the multiplier alone would give 12.
    """
    assert MIN_CANDIDATES == 25


@pytest.mark.parametrize(
    "heading",
    [
        "### Full result lists, unfiltered vs filtered",
        "### The retrieval that embarrassed us",
        "### Ingest scope",
        "### Code diff",
        "## 15. Bonus: MMR over the fused candidate list",
    ],
)
def test_results_md_carries_every_graded_artifact(heading):
    """
    Each of these is a separate line item on a rubric, and each is generated by
    a different part of the two scripts. Losing one is silent otherwise: the
    report still renders and still looks complete.
    """
    assert heading in RESULTS.read_text(encoding="utf-8"), heading


def test_hit_rates_are_reported_as_a_count_not_only_a_percentage():
    """
    The Week 3 task asks for hit-in-top-5 as a number out of 8. A percentage
    alone hides that one question is 12.5 points on a set this small.
    """
    assert "8/8 (100%)" in RESULTS.read_text(encoding="utf-8")
